#possible keybindings
#https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs

#Mod4 = Super key
modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
#tags = ["", "", "", "", "", "", "", "", ""]
#tags = ["www", "edit", "gimp", "inkscape", "meld", "video","vm", "files", "music"]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
scratchpad = []
#[[scratchpad]]
#name = "MainTerminal" # This is the name which is referenced when calling (case-sensitive)
#value = "xfce4-terminal" # The command to load the application if it isn't started
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
#focus_behaviour = "Driven"
#focus_behaviour = "ClickTo"
focus_new_windows = false

[[keybind]]
command = "Execute"
value = "xfce4-terminal --drop-down"
modifier = []
key = "F12"

#[[keybind]]
#command = "ToggleScratchPad"
#value = "MainTerminal"
#modifier = []
#key = "F12"

[[keybind]]
command = "Execute"
value = "killall conky"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "Execute"
value = "rofi -no-config -no-lazy-grab -show run -theme $HOME/.config/leftwm/themes/current/rofi/launcher.rasi"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "archlinux-logout"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "Execute"
value = "nemo"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey","Shift"]
key = "f"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down" 

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "underscore"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\""
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\""
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\""
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\""
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\""
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\""
modifier = ["modkey", "Shift"]
key = "minus"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\""
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\""
modifier = ["modkey", "Shift"]
key = "underscore"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\""
modifier = ["modkey", "Shift"]
key = "ccedilla"

[[keybind]]
command = "IncreaseMainWidth"
value = "1"
modifier = ["modkey", "Control"]
key = "Right"

[[keybind]]
command = "DecreaseMainWidth"
value = "1"
modifier = ["modkey", "Control"]
key = "Left"

[[keybind]]
command = "Execute"
value = "flameshot gui"
key = "Menu"
