border_width = 1 
margin = 5
workspace_margin = 5 
# default_width = 1280
# default_height = 720
# always_float = false
default_border_color = "#1E1F29"
floating_border_color = "#1E1F29"
focused_border_color = "#1E1F29"
